name: 'build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test
      - name: Build Examples 
        run: cargo build --examples
